### ISSUE TITLE
Does not work on Ubuntu20.04 LTS due to libsnmp30 dependency

### ISSUE THREAD

**Issue by ghpqans** [MichalMazurek/easysnmp2#7]
The newest `easysnmp2` version  `0.3.1` needs `libsnmp30`, but Ubuntu only provides `libsnmp35`.
Is it possible to allow newer `libsnmp` versions or lower the version restrictions?

```
$ uname -a
Linux mycomputer 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```
```
Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import easysnmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.10/site-packages/easysnmp/__init__.py", line 1, in <module>
    from easysnmp.easy import (  # noqa
  File ".../.venv/lib/python3.10/site-packages/easysnmp/easy.py", line 3, in <module>
    from easysnmp.session import Session
  File ".../.venv/lib/python3.10/site-packages/easysnmp/session.py", line 8, in <module>
    from easysnmp import interface
ImportError: libnetsnmp.so.30: cannot open shared object file: No such file or directory
```
```
(.venv) $ pip list --local
Package            Version
------------------ ---------
[...]
easysnmp2          0.3.1
```
```
apt list libsnmp*
Auflistung... Fertig
libsnmp-base/focal-updates,focal-updates,now 5.8+dfsg-2ubuntu2.9 all  [installiert]
[...]
libsnmp35/focal-updates,now 5.8+dfsg-2ubuntu2.9 amd64  [installiert]
```

**Comment by ghpqans** [comment]
I tried to install `libsnmp30` via `.deb` package from http://ftp.de.debian.org/debian/pool/main/n/net-snmp/.
However, it fails due to 
```
sudo gdebi libsnmp30_5.7.3+dfsg-5+deb10u2_amd64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Dieses Paket kann nicht installiert werden
Dependency is not satisfiable: libperl5.28 (>= 5.28.0)
```
